program_settings:
  #### Path to export wallet data
  export_path: "data"

  #### Export settings
  # csv or txt
  export_format: "csv"

  # set True if you want results to be exported to a file
  # set False if you don't want results to be exported
  export_enabled: True

  #### Logging setting
  logging_level: "INFO" # Options: DEBUG, INFO, WARNING

plugin_settings:
  #### Wallet Search settings
  # timeframe options - 1d, 7d, 30d
  #
  # wallet tags options -
  #   all = all tags
  #   pump_smart = Pump.Fun Smart Money
  #   smart_degen = Smart Money (default)
  #   reowned = KOL/VC/Influencer
  #   snipe_bot = Snipe Bot
  #
  # winrate - set 0 to 100 (default is 60)

  TopWallets:
    timeframe: "7d"
    wallet_tag: "smart_degen"
    win_rate: 80

  SolanaWalletScanner:
    timeframe: "7d"